server:
  port: 8181

spring:
  profiles:
    active: local
  application:
    name: complaints-back
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none

