services:
  complaints-backend:
    container_name: complaints-backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8181
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/complaints_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: complaints_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d complaints_db" ]
      interval: 2s
      timeout: 10s
      retries: 10